"""Repository-side convergence control records and authority contracts.

The module intentionally exposes no production authority constructor that can
succeed before an operator-approved substrate is implemented and bound.
"""

from ._authority import (
    AuthorityBackend,
    AuthorityRole,
    AuthorityUnavailable,
    ForbiddenAuthoritySubstrate,
    NonPromotionalEvidence,
    OperationBinding,
    ProductionTopology,
    SubstrateBinding,
    production_authority,
    require_promotable,
)
from ._evaluation import (
    ActiveContractContext,
    Applicable,
    ApplicableUnknown,
    Attestation,
    AttestationOutcome,
    ConditionalApplicability,
    Currency,
    DependencyBinding,
    DependencyKey,
    EvaluationInputError,
    EvidenceDidNotPass,
    EvidenceEvaluation,
    EvidenceNotCurrent,
    EvidenceUnknown,
    GateAssignment,
    GateImpact,
    InvalidationEvent,
    InvalidationPolicy,
    NonPromotionalContext,
    NotApplicable,
    NotDue,
    PredicateProof,
    PreassemblyContext,
    PromotionAssessment,
    SeparationPolicy,
    UnconditionalApplicability,
    UnknownReason,
    ValidityPolicy,
    apply_invalidation,
    evaluate_evidence,
    require_evaluation_pass,
    require_promotable_evidence,
)
from ._records import (
    MAX_NESTING_DEPTH,
    MAX_RECORD_BYTES,
    RECORD_KINDS,
    RECORD_SCHEMAS,
    CanonicalizationError,
    ControlRecord,
    ControlRecordError,
    PrivacyEnvelopeError,
    RecordErrorCode,
    RecordValidationError,
)
from ._promotion import admit_promotion


__all__ = [
    "AuthorityBackend",
    "AuthorityRole",
    "AuthorityUnavailable",
    "ForbiddenAuthoritySubstrate",
    "NonPromotionalEvidence",
    "OperationBinding",
    "ProductionTopology",
    "SubstrateBinding",
    "production_authority",
    "require_promotable",
    "ActiveContractContext",
    "Applicable",
    "ApplicableUnknown",
    "Attestation",
    "AttestationOutcome",
    "CanonicalizationError",
    "ConditionalApplicability",
    "ControlRecord",
    "ControlRecordError",
    "Currency",
    "DependencyBinding",
    "DependencyKey",
    "EvaluationInputError",
    "EvidenceDidNotPass",
    "EvidenceEvaluation",
    "EvidenceNotCurrent",
    "EvidenceUnknown",
    "GateAssignment",
    "GateImpact",
    "InvalidationEvent",
    "InvalidationPolicy",
    "MAX_NESTING_DEPTH",
    "MAX_RECORD_BYTES",
    "NonPromotionalContext",
    "NotApplicable",
    "NotDue",
    "PredicateProof",
    "PreassemblyContext",
    "PrivacyEnvelopeError",
    "PromotionAssessment",
    "RECORD_KINDS",
    "RECORD_SCHEMAS",
    "RecordErrorCode",
    "RecordValidationError",
    "SeparationPolicy",
    "UnconditionalApplicability",
    "UnknownReason",
    "ValidityPolicy",
    "apply_invalidation",
    "admit_promotion",
    "evaluate_evidence",
    "require_evaluation_pass",
    "require_promotable_evidence",
]
